# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{
    "name" : "Childcare Management / Nursery Management",
    "version" : "15.0.0.5",
    "category" : "Industries",
    'summary': "Child care management Childcare nursery management child school management child nursery management babycare management child admission process child class room children care management children nursery playgroup management kindergarten child play centre",
    "description": """
    This odoo app helps user to manage childcare, Portal user can submit a admission inquiry from portal and user can see inquiry confirm inquiry, enroll inquiry, on enroll child and parent are created from inquiry, assign classroom of school to childs, create invoice for school fees, add nutrition, allergy and medicine for childs. User can also mange supply chain management, create supply request, approve request and create purchased order for supply request. user can sign in or sign out, check attendance of staff and child and print attendance report.
    
    """,
    "author": "BrowseInfo",
    "website" : "https://www.browseinfo.in",
    "price": 399,
    "currency": 'EUR',
    "depends" : ["base","portal","sales_team","hr","hr_attendance","web","website","crm","account_payment","purchase","stock","sms","payment","account","mail"],
    "data": [
        "security/bi_morpho_childcare_management.xml",
        "security/ir.model.access.csv",
        "data/cc_data.xml",
        "data/cc_sequences_data.xml",         
        "data/cc_enroll_confirm_mail_template.xml",         
        "data/cc_emergency_alert_template.xml",         
        "data/cc_parent_msg_template.xml",         
        "report/cc_reports_template.xml",         
        "report/cc_attendance_report_template.xml",         
        "report/cc_report.xml",         
        "wizard/cc_add_parent_views.xml",  
        "wizard/cc_waitlist_confirmation_wizard_views.xml",  
        "wizard/cc_lesson_plan_wizard_views.xml",  
        "wizard/cc_emergency_alert_wizard_views.xml",  
        "wizard/cc_parent_msg_wizard_views.xml",  
        "wizard/cc_media_sharing_wizard_views.xml",  
        "wizard/cc_user_staff_linking_wizard_views.xml",  
        "wizard/cc_print_attendance_views.xml",  
        "views/cc_nutrition_meal_config_views.xml",  
        "views/cc_staff_degree_views.xml",  
        "views/cc_staff_certificate_views.xml",  
        "views/cc_website_template.xml",  
        "views/cc_addmission_template.xml",  
        "views/cc_enquiry_confirm_template.xml",  
        "views/cc_child_views.xml",  
        "views/cc_doctor_views.xml",  
        "views/cc_room_views.xml",  
        "views/cc_note_views.xml",  
        "views/cc_staff_views.xml",  
        "views/cc_parent_views.xml",  
        "views/cc_school_views.xml",  
        "views/cc_attendance_views.xml",  
        "views/cc_product_inherit_views.xml",  
        "views/cc_child_leads_views.xml",  
        "views/cc_account_move_inherit_views.xml",  
        "views/cc_supply_chain_views.xml",  
        "views/cc_child_attendance_views.xml",  
        "views/menus_views.xml",  
    ],
    "assets": {
        "web.assets_backend": [
            "bi_morpho_childcare_management/static/src/js/cc_attendance.js"
        ],
        "web.assets_common": [
            "bi_morpho_childcare_management/static/src/scss/cc_addmission_style.scss",
            "bi_morpho_childcare_management/static/src/js/cc_addmission_form.js",
            "bi_morpho_childcare_management/static/src/js/cc_enquiry_confirm_form.js",
            "bi_morpho_childcare_management/static/src/scss/cc_website_style.scss",
            "bi_morpho_childcare_management/static/src/js/cc_website_template.js",
        ],
        "web.assets_qweb": [
            "bi_morpho_childcare_management/static/src/xml/cc_portal_chatter.xml",
        ],
    },
    "auto_install": False,
    "installable": True,
    "live_test_url":"https://youtu.be/tWc0Qq_VAoM",
    "images":["static/description/Banner.png"],
    "uninstall_hook" : "bi_uninstall_hook",
    "license" : "OPL-1",
}
